import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0e131e",
        surface: {
          DEFAULT: "#0e131e",
          dim: "#0e131e",
          bright: "#343946",
          "container-lowest": "#090e19",
          container: "#1b1f2b",
          "container-low": "#171b27",
          "container-high": "#252a36",
          "container-highest": "#303541",
        },
        primary: {
          DEFAULT: "#adc6ff",
          container: "#4d8eff",
          fixed: "#d8e2ff",
          "fixed-dim": "#adc6ff",
        },
        secondary: {
          DEFAULT: "#4cd7f6",
          container: "#03b5d3",
          fixed: "#acedff",
          "fixed-dim": "#4cd7f6",
        },
        tertiary: {
          DEFAULT: "#ffb786",
          container: "#df7412",
          fixed: "#ffdcc6",
          "fixed-dim": "#ffb786",
        },
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        "on-primary": "#002e6a",
        "on-secondary": "#003640",
        "on-tertiary": "#502400",
        "on-error": "#690005",
        "on-surface": "#dee2f2",
        "on-surface-variant": "#c2c6d6",
        "on-background": "#dee2f2",
        "on-primary-container": "#00285d",
        "on-secondary-container": "#00424e",
        "on-tertiary-container": "#461f00",
        "on-primary-fixed": "#001a42",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        "on-tertiary-fixed": "#311400",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed-variant": "#723600",
        "on-error-container": "#ffdad6",
        "surface-tint": "#adc6ff",
        "surface-variant": "#303541",
        outline: {
          DEFAULT: "#8c909f",
          variant: "#424754",
        },
        "inverse-surface": "#dee2f2",
        "inverse-on-surface": "#2b303c",
        "inverse-primary": "#005ac2",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "h1-desktop": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "h1-mobile": ["36px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "800" }],
        "h2-desktop": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h2-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h3-desktop": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "h3-mobile": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "body": ["16px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "tag-label": ["13px", { lineHeight: "1", letterSpacing: "2px", fontWeight: "500" }],
        "code": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      spacing: {
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "stack-xl": "48px",
        "gutter": "24px",
        "section-mobile": "60px",
        "section-desktop": "120px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      maxWidth: {
        container: "1200px",
        content: "780px",
      },
    },
  },
  plugins: [],
};

export default config;
